In [26]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
customer = pd.read_csv('rts_mar20qtr-tables-csv.csv')
customer.head(5)

Series_reference   Period  Data_value Suppressed STATUS    UNITS  Magnitude  \
0      RTTA.SF11CA  1997.03     27070.4        NaN      F  Dollars          6   
1      RTTA.SF11CA  1998.03     27748.4        NaN      F  Dollars          6   
2      RTTA.SF11CA  1999.03     28216.6        NaN      F  Dollars          6   
3      RTTA.SF11CA  2000.03     30204.1        NaN      F  Dollars          6   
4      RTTA.SF11CA  2001.03     31641.6        NaN      F  Dollars          6   

                         Subject  \
0  Retail Trade (ANZSIC06) - RTT   
1  Retail Trade (ANZSIC06) - RTT   
2  Retail Trade (ANZSIC06) - RTT   
3  Retail Trade (ANZSIC06) - RTT   
4  Retail Trade (ANZSIC06) - RTT   

                                               Group         Series_title_1  \
0  Sales and stocks by industry, in current and c...  Core industries total   
1  Sales and stocks by industry, in current and c...  Core industries total   
2  Sales and stocks by industry, in current and c...  Core industries total   
3  Sales and stocks by industry, in current and c...  Core industries total   
4  Sales and stocks by industry, in current and c...  Core industries total   

             Series_title_2 Series_title_3 Series_title_4  Series_title_5  
0  Sales (operating income)        Current         Actual             NaN  
1  Sales (operating income)        Current         Actual             NaN  
2  Sales (operating income)        Current         Actual             NaN  
3  Sales (operating income)        Current         Actual             NaN  
4  Sales (operating income)        Current         Actual             NaN

# ML part

In [27]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [28]:
y = customer[['Data_value']]
x = customer[['Period']]
y.head(),x.head()

(   Data_value
 0     27070.4
 1     27748.4
 2     28216.6
 3     30204.1
 4     31641.6,
     Period
 0  1997.03
 1  1998.03
 2  1999.03
 3  2000.03
 4  2001.03)

In [29]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30,random_state = 0)
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((15280, 1), (15280, 1), (6549, 1), (6549, 1))

In [30]:
regressor = LinearRegression()
# regressor.fit(x_train, y_train)   --------valueError

In [31]:
# y_pred = regressor.predict(x_test)    -------NotfittedError

In [32]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test,  y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [6549, 7641]

In [33]:
# y_pred = regressor.predict(x_test)    -------NotfittedError

In [34]:
x_train[:5], y_train[:5]

(        Period
 9858   1997.09
 19284  2002.12
 2416   2017.12
 7218   2005.12
 11905  2014.06,
        Data_value
 9858         15.6
 19284        52.6
 2416          1.2
 7218        410.3
 11905      1565.6)

In [35]:
x = customer[['Period']]
y = customer[['Magnitude']]

In [36]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.35,random_state = 0)

In [37]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()
log_model.fit(x_train, y_train)

C:\Users\Yograj\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Yograj\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [38]:
y_pred = log_model.predict(x_test)

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [40]:
confusion_matrix(y_test, y_pred),accuracy_score(y_test, y_pred)

(array([[   0, 1008],
        [   0, 6633]], dtype=int64),
 0.8680800942285041)

In [41]:
x = customer[['Period']]
y = customer[['Magnitude']]

In [42]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20,random_state = 0)

In [44]:
from sklearn.tree import DecisionTreeClassifier
my_tree = DecisionTreeClassifier()
my_tree.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [45]:
my_tree.predict(x_test)

array([6, 6, 6, ..., 6, 6, 6], dtype=int64)

In [46]:
y_pred = my_tree.predict(x_test)

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred),accuracy_score(y_test, y_pred)

(array([[   0,  581],
        [   0, 3785]], dtype=int64),
 0.8669262482821805)

In [48]:
(3785)/(581+3785)

0.8669262482821805

In [50]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train, y_train)

C:\Users\Yograj\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Yograj\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [53]:
rf.predict(x_test)

array([6, 6, 6, ..., 6, 6, 6], dtype=int64)

In [ ]:
y_pred = rf.predict(x_test)

In [52]:
confusion_matrix(y_test, y_pred)

array([[   0,  581],
       [   0, 3785]], dtype=int64)