# 1D array

In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
a[1]

2

In [5]:
a

array([1, 2, 3])

In [6]:
a[1:2]

array([2])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[0:]

array([1, 2, 3])

In [9]:
a[:2]

array([1, 2])

# 2D array

In [10]:
b=np.array([[1,2,3],
            [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
b[0]

array([1, 2, 3])

In [12]:
b[1][0]

4

In [13]:
b[1]

array([4, 5, 6])

In [16]:
b[:0]

array([], shape=(0, 3), dtype=int32)

In [14]:
b[:1]

array([[1, 2, 3]])

In [15]:
b[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b[1:]

array([[4, 5, 6]])

# initializing numpy array

In [19]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
d=np.arange(10,25,5)
print(d)

[10 15 20]


In [21]:
d=np.arange(10,20,2)
print(d)

[10 12 14 16 18]


In [24]:
e=np.linspace(5,6,10)
print(e)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]


In [25]:
x=np.full((3,3),5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [26]:
y=np.random.random((3,4))
print(y)

[[0.39804844 0.43934593 0.00611749 0.21154072]
 [0.37154614 0.65304505 0.66366918 0.24477575]
 [0.14214851 0.57957172 0.05568263 0.76596725]]


# numpy array inspection

In [29]:
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [42]:
b.shape=(3,2)
print(b)
print("\n")
print(b.shape[0])
print(b.shape[1])
print("Dimension of array : ",b.ndim,"D")
print("Dimension of array : ",a.ndim,"D")

[[1 2]
 [3 4]
 [5 6]]


3
2
Dimension of array :  2 D
Dimension of array :  1 D


In [32]:
a1=np.arange(24)
a1.size

24

In [33]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
a1.dtype

dtype('int32')

In [44]:
a2=np.linspace(5,7,11)
print(a2.dtype)
print(a2)

float64
[5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7. ]


# numpy array mathematics

In [52]:
x1=np.array([5,6])
x2=np.array([3,4])
print(np.sum(a))
print(np.sum(x1))


6
11


In [53]:
print(np.subtract(x1,x2))

[2 2]


In [59]:
print(np.sum([8,4]))
print(np.subtract(8,4))
print(np.divide(8,4))
print(np.multiply(8,4))
print(np.exp(8))
print(np.sqrt(8))
print(np.sin(90))
print(np.cos(90))
print(np.log(8))

12
4
2.0
32
2980.9579870417283
2.8284271247461903
0.8939966636005579
-0.4480736161291701
2.0794415416798357


In [61]:
np.sum([[0,1],[0,5]],axis=0)

array([0, 6])

In [62]:
np.sum([[0,1],[0,5]],axis=1)

array([1, 5])